version: "3.4"
services:
  centos7vspherebuild:
    volumes:
      - rpms:/root/rpmbuild/SRPMS
      - rpm7:/root/rpmbuild/RPMS
    build:
      context: .

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
